using System.Collections.Generic;
using Game.Content.Features.SpacePaths;
using Game.Core.Coordinates;
using Game.Core.Rendering;
using Unity.Mathematics;
using UnityEngine;

#pragma warning disable CS0618 // IIslandPlatformDrawer is obsolete, but it is how space paths draw.

namespace QuinnBast.Shapez2.TrainCargoTools
{
    /// Draws a cargo belt's own track.
    ///
    /// This is the fifth attempt at making a cargo belt distinguishable from an ordinary one, and
    /// the first four all shared a mistake worth recording: they decorated something that still
    /// looked exactly like a space belt.
    ///
    ///   - Four posts at the chunk corners read as *damage* - pillars at the edge of a belt look
    ///     like something snapped off.
    ///   - Low guard rails along the run were worse on corners: a mesh authored straight cannot
    ///     follow a bend, so they jutted out of the outside of every curve like loose sticks.
    ///   - An accent-palette tint reaches only the trim and the direction arrows. The deck plane
    ///     has no per-instance buffer at all, and feeding it one makes the mesh *vanish* rather
    ///     than ignore the data - a belt became a pair of floating edges.
    ///   - A coloured wash under the deck was simply too quiet to notice.
    ///
    /// The track is now the mod's own geometry: a channel section with walls and sleepers, swept
    /// along a real arc for the corners. It differs at every zoom and from every angle, and there
    /// is nothing bolted on to be misread. Generated by Tools/generate_meshes.py, where the sweep
    /// lives.
    ///
    /// The overview map still uses vanilla's reduced mesh. A map blip wants the ordinary silhouette
    /// and `MeshBuilder.AddTranslateRotate` wants a `UnityMeshReference`, which a runtime-loaded
    /// mesh is not.
    internal sealed class CargoTrackDrawer : IIslandPlatformDrawer
    {
        private readonly ISpacePathResources Track;
        private readonly PathNodeClassification Run;
        private readonly ILODMeshMaterial Mesh;

        /// The island's chunk layers, lowest first. One entry for everything but a lift, which
        /// is a stack of two or three - see TrainCargoToolsMod.ChunkData.
        ///
        /// A platform drawer is called **once per island**, not once per chunk
        /// (`CustomPlatformsDrawer.Draw` passes the island's own transform), so an island that
        /// spans layers has to draw every one of them itself. A lift left to draw a single deck
        /// shows track at its foot and nothing above.
        private readonly int[] Layers;

        /// The mesh is the whole deck. It was one of three stacked tiers until the lane layers
        /// were moved to ride abreast on a single deck - see CargoLanes.Across_W.
        public CargoTrackDrawer(
            ISpacePathResources track, PathNodeClassification run, ILODMeshMaterial mesh,
            int[] layers = null)
        {
            Track = track;
            Run = run;
            Mesh = mesh;
            Layers = layers ?? OneLayer;
        }

        private static readonly int[] OneLayer = { 0 };

        /// A chunk is twenty world units tall, so a layer of a lift sits twenty above the last.
        private const float LayerHeight_W = 20f;

        public void Draw(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, LODMaterialAsset materialProvider, float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference material))
            {
                return;
            }

            // One tier. It briefly was three, one per lane layer, back when the layers were
            // stacked vertically - and three decks three units apart made a six-unit tower whose
            // top deck hid the two below it. The layers ride abreast on this one deck now, so
            // the tier that carries them is single again. See CargoLanes.Across_W.
            //
            // The height is read from the theme rather than baked into the mesh, because how
            // high a space path floats is authored data.
            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            foreach (int layer in Layers)
            {
                drawOptions.Renderers.SpacePaths.Add(
                    mesh, material,
                    Trs(transform, scale, CargoLanes.DeckHeight_W(config) + layer * LayerHeight_W));
            }
        }

        private static Matrix4x4 Trs(in GlobalChunkTransform transform, float3 scale, float height)
        {
            return Matrix4x4.TRS(
                (Vector3)transform.Position.ToCenter_W(height),
                FastMatrix.RotateY(transform.Rotation), (Vector3)scale);
        }

        public void DrawBlueprint(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, MaterialPropertyBlock propertyBlock,
            PropertyBlockHash propertyBlockHash, float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference _))
            {
                return;
            }

            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            float3 centre = transform.Position.ToCenter_W(CargoLanes.DeckHeight_W(config));
            float3 offset = IslandsBlueprintDrawUtils.GetCameraPositionOffset(drawOptions, centre);

            Matrix4x4 trs = Matrix4x4.TRS(
                (Vector3)(centre + offset),
                FastMatrix.RotateY(transform.Rotation), (Vector3)scale);

            IslandsBlueprintDrawUtils.DrawBlueprintMesh(
                drawOptions, mesh, trs, propertyBlock, propertyBlockHash);
        }

        public void DrawBlueprintNonInstanced(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, MaterialPropertyBlock propertyBlock,
            float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference _))
            {
                return;
            }

            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            float3 centre = transform.Position.ToCenter_W(CargoLanes.DeckHeight_W(config));
            float3 offset = IslandsBlueprintDrawUtils.GetCameraPositionOffset(drawOptions, centre);

            Matrix4x4 trs = Matrix4x4.TRS(
                (Vector3)(centre + offset),
                FastMatrix.RotateY(transform.Rotation), (Vector3)scale);

            IslandsBlueprintDrawUtils.DrawBlueprintMeshNonInstanced(
                drawOptions, mesh, trs, propertyBlock);
        }

        /// The zoomed-out map builds one static mesh, so a belt that drew nothing here would
        /// disappear in the overview while every belt around it stayed.
        public void DrawOverview(MeshBuilder builder, in GlobalChunkTransform transform)
        {
            WorldCoordinate position = transform.Position.ToCenter_W(-2.07314f);
            builder.AddTranslateRotate(Track.GetReducedMesh(Run), position, transform.Rotation);
        }
    }
}
