using System.Collections.Generic;
using Game.Content.Features.SpacePaths;
using Game.Core.Coordinates;
using Game.Core.Rendering;
using Unity.Mathematics;
using UnityEngine;

#pragma warning disable CS0618 // IIslandPlatformDrawer is obsolete, but it is how space paths draw.

namespace TrainCargoTools
{
    /// Draws a cargo belt's own track.
    ///
    /// This is the fifth attempt at making a cargo belt distinguishable from an ordinary one, and
    /// the first four all shared a mistake worth recording: they decorated something that still
    /// looked exactly like a space belt.
    ///
    ///   - Four posts at the chunk corners read as *damage* - pillars at the edge of a belt look
    ///     like something snapped off.
    ///   - Low guard rails along the run were worse on corners: a mesh authored straight cannot
    ///     follow a bend, so they jutted out of the outside of every curve like loose sticks.
    ///   - An accent-palette tint reaches only the trim and the direction arrows. The deck plane
    ///     has no per-instance buffer at all, and feeding it one makes the mesh *vanish* rather
    ///     than ignore the data - a belt became a pair of floating edges.
    ///   - A coloured wash under the deck was simply too quiet to notice.
    ///
    /// The track is now the mod's own geometry: a channel section with walls and sleepers, swept
    /// along a real arc for the corners. It differs at every zoom and from every angle, and there
    /// is nothing bolted on to be misread. Generated by Tools/generate_meshes.py, where the sweep
    /// lives.
    ///
    /// The overview map still uses vanilla's reduced mesh. A map blip wants the ordinary silhouette
    /// and `MeshBuilder.AddTranslateRotate` wants a `UnityMeshReference`, which a runtime-loaded
    /// mesh is not.
    internal sealed class CargoTrackDrawer : IIslandPlatformDrawer
    {
        private readonly ISpacePathResources Track;
        private readonly PathNodeClassification Run;
        private readonly ILODMeshMaterial Mesh;

        /// The mesh is one *tier*. A belt has three, one per lane layer, stacked by the drawer
        /// at the same offsets the cargo renderer uses - see Draw.
        public CargoTrackDrawer(
            ISpacePathResources track, PathNodeClassification run, ILODMeshMaterial mesh)
        {
            Track = track;
            Run = run;
            Mesh = mesh;
        }

        public void Draw(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, LODMaterialAsset materialProvider, float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference material))
            {
                return;
            }

            // One tier per lane layer, at exactly the heights the cargo renderer puts containers
            // at. A single tier was wrong in a way that only shows once something is on the belt:
            // layers 1 and 2 sit lower, so their containers sank through the floor of the model.
            //
            // The offsets are read from the theme rather than baked into the mesh, because how
            // far apart a space path's layers sit is authored data.
            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            for (int layer = 0; layer < SpacePathConstants.NumLayers; layer++)
            {
                float height = CargoLanes.LayerHeight_W(config, layer);
                drawOptions.Renderers.SpacePaths.Add(
                    mesh, material, Trs(transform, scale, height));
            }
        }

        private static Matrix4x4 Trs(in GlobalChunkTransform transform, float3 scale, float height)
        {
            return Matrix4x4.TRS(
                (Vector3)transform.Position.ToCenter_W(height),
                FastMatrix.RotateY(transform.Rotation), (Vector3)scale);
        }

        public void DrawBlueprint(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, MaterialPropertyBlock propertyBlock,
            PropertyBlockHash propertyBlockHash, float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference _))
            {
                return;
            }

            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            for (int layer = 0; layer < SpacePathConstants.NumLayers; layer++)
            {
                float3 centre = transform.Position.ToCenter_W(
                    CargoLanes.LayerHeight_W(config, layer));
                float3 offset = IslandsBlueprintDrawUtils.GetCameraPositionOffset(drawOptions, centre);

                Matrix4x4 trs = Matrix4x4.TRS(
                    (Vector3)(centre + offset),
                    FastMatrix.RotateY(transform.Rotation), (Vector3)scale);

                IslandsBlueprintDrawUtils.DrawBlueprintMesh(
                    drawOptions, mesh, trs, propertyBlock, propertyBlockHash);
            }
        }

        public void DrawBlueprintNonInstanced(
            FrameDrawOptions drawOptions, in GlobalChunkTransform transform,
            IIslandConfiguration islandConfiguration, MaterialPropertyBlock propertyBlock,
            float3 scale)
        {
            if (!Mesh.TryGet(drawOptions.LOD.IslandLOD, drawOptions.LOD.IslandMaterialLOD,
                    out IMeshReference mesh, out IMaterialReference _))
            {
                return;
            }

            SpacePathItemRenderingConfig config = Track.ItemRenderingConfig;

            for (int layer = 0; layer < SpacePathConstants.NumLayers; layer++)
            {
                float3 centre = transform.Position.ToCenter_W(
                    CargoLanes.LayerHeight_W(config, layer));
                float3 offset = IslandsBlueprintDrawUtils.GetCameraPositionOffset(drawOptions, centre);

                Matrix4x4 trs = Matrix4x4.TRS(
                    (Vector3)(centre + offset),
                    FastMatrix.RotateY(transform.Rotation), (Vector3)scale);

                IslandsBlueprintDrawUtils.DrawBlueprintMeshNonInstanced(
                    drawOptions, mesh, trs, propertyBlock);
            }
        }

        /// The zoomed-out map builds one static mesh, so a belt that drew nothing here would
        /// disappear in the overview while every belt around it stayed.
        public void DrawOverview(MeshBuilder builder, in GlobalChunkTransform transform)
        {
            WorldCoordinate position = transform.Position.ToCenter_W(-2.07314f);
            builder.AddTranslateRotate(Track.GetReducedMesh(Run), position, transform.Rotation);
        }
    }
}
