using System;
using System.Collections.Generic;
using ShapezShifter.Kit;
using UnityEngine;
using ILogger = Core.Logging.ILogger;

namespace QuinnBast.Shapez2.TrainCargoTools
{
    /// The six machine meshes, loaded from Resources/*.obj once and kept for the process.
    ///
    /// The belts are not here. A cargo belt draws with the game's own space belt and pipe track
    /// meshes off the visual theme - see CargoAppearance - because a cargo line has to read as a
    /// line, and nothing hand-made was going to sit next to vanilla track without looking like a
    /// different game. Only the machines needed geometry that does not already exist.
    ///
    /// The .obj files are generated by Tools/generate_meshes.py, which is where the shapes and the
    /// reasoning about them live. Nothing here depends on that: the loader goes by filename, so a
    /// file replaced out of Blender is picked up with no code change.
    internal sealed class CargoMeshes
    {
        /// Loaded eagerly in the mod constructor rather than on first draw. Mesh loading goes
        /// through Assimp and allocates a Unity Mesh; doing it inside a frame would be a visible
        /// hitch, and doing it once is what the loaded results are for.
        private readonly Dictionary<string, LOD6Mesh> ByName = new Dictionary<string, LOD6Mesh>();

        /// The raw meshes as well as their LOD wrappers, because the UVs get rewritten after
        /// load - see ApplyPalette.
        private readonly Dictionary<string, Mesh> RawByName = new Dictionary<string, Mesh>();

        /// Each mesh's UVs exactly as the file held them, kept because ApplyPalette edits the
        /// live mesh in place and so destroys the sentinels it matches on.
        ///
        /// It got away without this while a resolved coordinate could never look like a
        /// sentinel: the five roles sat in the bottom-left corner of UV space and the sampled
        /// coordinates did not. Resolving against the material palette removes that guarantee -
        /// the search window is wherever the art is - and a second pass, which `cargotools.uv`
        /// makes on every change, would then re-map a coordinate that had already been resolved.
        private readonly Dictionary<string, Vector2[]> PristineUVs = new Dictionary<string, Vector2[]>();

        /// One mesh stands in for all six levels of detail.
        ///
        /// These are ~400-600 triangle single-chunk platforms, so the LOD ladder buys little, and
        /// LodMeshBuilder's slot mapping is scrambled anyway - BuildLod6Mesh assigns MeshAt(3) to
        /// LODMinimal, MeshAt(4) to LODOverview and MeshAt(5) to LODReduced, which do not line up
        /// with LOD6Mesh's own switch. With one mesh supplied, MeshAt falls back to the last entry
        /// for every level, so all six slots get the same mesh and the mismapping cannot bite.
        /// Supplying real per-level meshes would walk straight into it.
        public CargoMeshes(ModFolderLocator resources, ILogger logger, params string[] names)
        {
            foreach (string name in names)
            {
                string path = resources.SubPath(name + ".obj");
                try
                {
                    Mesh mesh = FileMeshLoader.LoadSingleMeshFromFile(path);
                    mesh.name = name;
                    RawByName[name] = mesh;
                    PristineUVs[name] = mesh.uv;
                    ByName[name] = MeshLod.Create().AddLod0Mesh(mesh).BuildLod6Mesh();
                }
                catch (Exception exception)
                {
                    // Deliberately not fatal, unlike the icon path. A missing icon leaves a blank
                    // button that looks broken; a missing mesh leaves the bare platform this mod
                    // shipped with before there was any art, which is merely plain. Taking the
                    // whole mod down over it would be the worse trade.
                    logger.Warning?.Log($"Could not load {path}: {exception.Message}");
                }
            }
        }

        public bool TryGet(string name, out LOD6Mesh lod)
        {
            return ByName.TryGetValue(name, out lod);
        }

        /// Rewrites every sentinel UV to the coordinate the palette resolved for that role.
        ///
        /// Safe to call repeatedly, because it matches against a copy of the UVs taken at load
        /// and never against whatever was written last time. That matters because cargotools.uv
        /// re-applies the whole palette after changing one role, and because the theme is
        /// resolved once per session while the meshes are loaded once per process.
        ///
        /// The LOD6Mesh wrappers do not need rebuilding: they hold references to these same Mesh
        /// objects, so editing the mesh in place is seen by everything already drawing it.
        public void ApplyPalette(CargoPalette palette, ILogger logger)
        {
            if (!palette.Ready)
            {
                return;
            }

            foreach (KeyValuePair<string, Mesh> entry in RawByName)
            {
                try
                {
                    if (!PristineUVs.TryGetValue(entry.Key, out Vector2[] authored)
                        || authored == null || authored.Length == 0)
                    {
                        continue;
                    }

                    // A fresh array each time. Writing into the cached one would turn it into
                    // whatever the last palette resolved to, which is the very thing it exists
                    // to avoid.
                    Vector2[] uvs = new Vector2[authored.Length];

                    for (int i = 0; i < authored.Length; i++)
                    {
                        uvs[i] = TryRole(authored[i], out string role)
                            && palette.TryGet(role, out Vector2 resolved)
                                ? resolved
                                : authored[i];
                    }

                    entry.Value.uv = uvs;
                }
                catch (Exception exception)
                {
                    logger.Warning?.Log($"Could not recolour {entry.Key}: {exception.Message}");
                }
            }
        }

        /// Which role a vertex was authored with, or none if this is not a sentinel.
        ///
        /// Compared with a tolerance rather than exactly: the .obj writes five decimal places
        /// and Assimp round-trips through float, so an exact match on 0.03 is not guaranteed.
        /// The sentinels are a whole 0.01 apart, so half of that is a generous window that
        /// still cannot confuse two roles.
        private static bool TryRole(Vector2 uv, out string role)
        {
            role = null;
            if (Mathf.Abs(uv.y - CargoPalette.SentinelV) > 0.004f)
            {
                return false;
            }

            for (int i = 0; i < CargoPalette.Roles.Length; i++)
            {
                if (Mathf.Abs(uv.x - CargoPalette.Sentinel(i).x) <= 0.004f)
                {
                    role = CargoPalette.Roles[i];
                    return true;
                }
            }

            return false;
        }

        /// Pairs one of the loaded meshes with a material from the visual theme.
        ///
        /// ModularIslandMeshDrawer.Module wants an ILODMeshMaterial, and the only implementation
        /// the game ships is LODMeshMaterialAsset - a ScriptableObject, authored in the editor,
        /// not constructible at runtime. The interface itself is public and has three members, so
        /// a mod supplies its own. That is the whole reason this type exists.
        ///
        /// The material comes from the theme rather than from the mod so the machines pick up
        /// whatever shading and palette the player's theme uses, the same as any vanilla island.
        internal sealed class ThemeMeshMaterial : ILODMeshMaterial
        {
            public ILODMesh LODMesh { get; }

            public ILODMaterial LODMaterial { get; }

            public ThemeMeshMaterial(ILODMesh mesh, ILODMaterial material)
            {
                LODMesh = mesh;
                LODMaterial = material;
            }

            /// Mesh LOD and material LOD are separate indices and the caller passes both; the
            /// game drops material detail faster than mesh detail. Copied from
            /// LODMeshMaterialAsset.TryGet, including clearing the other out parameter on failure
            /// so a half-resolved pair never reaches a draw call.
            public bool TryGet(
                int meshLod, int materialLod, out IMeshReference mesh, out IMaterialReference material)
            {
                if (!LODMesh.TryGet(meshLod, out mesh))
                {
                    material = null;
                    return false;
                }

                if (!LODMaterial.TryGet(materialLod, out material))
                {
                    mesh = null;
                    return false;
                }

                return true;
            }
        }
    }
}
